version: '3.8'

services:
  db:
    hostname: db
    image: ankane/pgvector
    ports:
     - 5432:5432
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres-data:/var/lib/postgresql/data


  # db:
  #   image: postgres:16.2-alpine
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: postgres
  
volumes:
  postgres-data:
